/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mca06
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/high_1.gif"))); // NOI18N
        jLabel10.setText("   1");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 300, 150));
        jLabel10.getAccessibleContext().setAccessibleName("jLabel10");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/high_2.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 300, 150));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/high_3.gif"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 300, 160));

        jLabel4.setForeground(new java.awt.Color(51, 0, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/high_4.gif"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, 150));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/high_5.gif"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 300, 150));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/high_6.gif"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 300, 140));

        jCheckBox1.setText("1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 50, 140));

        jCheckBox2.setText("2");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, 140));

        jCheckBox3.setText("3");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, 140));

        jCheckBox4.setText("4");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, 140));

        jCheckBox5.setText("5");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, 140));

        jCheckBox6.setText("6");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, 140));

        jButton1.setText("Its Magic Here");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 670, 50));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Answer Here");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 90, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newwww.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 290, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newwww.jpg"))); // NOI18N
        jLabel14.setText("jLabel11");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 290, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-6.jpg"))); // NOI18N
        jLabel9.setText("jLabel8");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 300, 130));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newwww.jpg"))); // NOI18N
        jLabel15.setText("jLabel11");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 280, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newwww.jpg"))); // NOI18N
        jLabel13.setText("jLabel11");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 290, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-6.jpg"))); // NOI18N
        jLabel12.setText("jLabel8");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 300, 130));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-6.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 280, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
   
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
 if(jCheckBox1.isSelected())
{jLabel1.setText(("1"));}
 
if(jCheckBox2.isSelected())
{jLabel1.setText("2");}

if(jCheckBox1.isSelected() && jCheckBox2.isSelected())
{jLabel1.setText("3");}
//hhhh
if(jCheckBox3.isSelected())  
{jLabel1.setText("4");}

if(jCheckBox3.isSelected() && jCheckBox1.isSelected())
{jLabel1.setText("5");}

if(jCheckBox2.isSelected() && jCheckBox3.isSelected())
{jLabel1.setText("6");}

if(jCheckBox2.isSelected() && jCheckBox1.isSelected() && jCheckBox3.isSelected())
{jLabel1.setText("7");}

if(jCheckBox4.isSelected())
{jLabel1.setText("8");}

if(jCheckBox1.isSelected() && jCheckBox4.isSelected())
{jLabel1.setText("9");}

if(jCheckBox2.isSelected() && jCheckBox4.isSelected())
{jLabel1.setText("10");}

if(jCheckBox2.isSelected() && jCheckBox1.isSelected() && jCheckBox4.isSelected())
{jLabel1.setText("11");}
if(jCheckBox4.isSelected() && jCheckBox3.isSelected())
{jLabel1.setText("12");}
if(jCheckBox1.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected())
{jLabel1.setText("13");}
if(jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected())
{jLabel1.setText("14");}
if(jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox1.isSelected())
{jLabel1.setText("15");}
if(jCheckBox5.isSelected())
{jLabel1.setText("16");}
if(jCheckBox1.isSelected()  && jCheckBox5.isSelected())
{jLabel1.setText("17");}
if(jCheckBox2.isSelected() && jCheckBox5.isSelected())
{jLabel1.setText("18");}
if(jCheckBox2.isSelected() && jCheckBox1.isSelected() && jCheckBox5.isSelected())
{jLabel1.setText("19");}
if(jCheckBox5.isSelected() && jCheckBox3.isSelected())
{jLabel1.setText("20");}
if(jCheckBox1.isSelected() && jCheckBox3.isSelected() && jCheckBox5.isSelected())
{jLabel1.setText("21");}

if(jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox5.isSelected())
{jLabel1.setText("22");}

if(jCheckBox2.isSelected() && jCheckBox1.isSelected() && jCheckBox3.isSelected() && jCheckBox5.isSelected())
{jLabel1.setText("23");}

if(jCheckBox5.isSelected() && jCheckBox4.isSelected())
{jLabel1.setText("24");}
if(jCheckBox4.isSelected() && jCheckBox5.isSelected() && jCheckBox1.isSelected())
{jLabel1.setText("25");}
if(jCheckBox2.isSelected() && jCheckBox4.isSelected() && jCheckBox5.isSelected())
{jLabel1.setText("26");}
if(jCheckBox2.isSelected() && jCheckBox1.isSelected() && jCheckBox4.isSelected() && jCheckBox5.isSelected())
{jLabel1.setText("27");}
if(jCheckBox4.isSelected() && jCheckBox3.isSelected() && jCheckBox5.isSelected())
{jLabel1.setText("28");}
if(jCheckBox1.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox5.isSelected())
{jLabel1.setText("29");}
if(jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox5.isSelected())
{jLabel1.setText("30");}
if(jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox1.isSelected() && jCheckBox5.isSelected())
{jLabel1.setText("31");}
if(jCheckBox6.isSelected())
{jLabel1.setText("32");}
if(jCheckBox1.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("33");}
if(jCheckBox2.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("34");}
if(jCheckBox2.isSelected() && jCheckBox1.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("35");}
if(jCheckBox6.isSelected() && jCheckBox3.isSelected() )
{jLabel1.setText("36");}
if(jCheckBox6.isSelected() && jCheckBox3.isSelected() && jCheckBox1.isSelected())
{jLabel1.setText("37");}
if(jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("38");}
if(jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox1.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("39");}
if(jCheckBox4.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("40");}
if(jCheckBox1.isSelected() && jCheckBox4.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("41");}
if(jCheckBox2.isSelected() && jCheckBox4.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("42");}
if(jCheckBox2.isSelected() && jCheckBox6.isSelected() && jCheckBox4.isSelected() && jCheckBox1.isSelected())
{jLabel1.setText("43");}
if(jCheckBox4.isSelected() && jCheckBox3.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("44");}
if(jCheckBox4.isSelected()&& jCheckBox1.isSelected() && jCheckBox6.isSelected() && jCheckBox3.isSelected())
{jLabel1.setText("45");}
if(jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox6.isSelected() && jCheckBox4.isSelected())
{jLabel1.setText("46");}
if(jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox1.isSelected() && jCheckBox4.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("47");}
if(jCheckBox5.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("48");}
if(jCheckBox1.isSelected() && jCheckBox5.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("49");}
if(jCheckBox2.isSelected() && jCheckBox5.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("50");}
if(jCheckBox2.isSelected() && jCheckBox1.isSelected() && jCheckBox5.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("51");}
if(jCheckBox5.isSelected() && jCheckBox3.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("52");}
if(jCheckBox1.isSelected() && jCheckBox3.isSelected() && jCheckBox6.isSelected() && jCheckBox5.isSelected())
{jLabel1.setText("53");}
if(jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox5.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("54");}
if(jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox5.isSelected() && jCheckBox6.isSelected() && jCheckBox1.isSelected())
{jLabel1.setText("55");}
if(jCheckBox4.isSelected() && jCheckBox5.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("56");}
if(jCheckBox1.isSelected()  && jCheckBox4.isSelected()  && jCheckBox5.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("57");}
if(jCheckBox2.isSelected() &&  jCheckBox4.isSelected() && jCheckBox5.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("58");}
if(jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox4.isSelected() && jCheckBox5.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("59");}
if(jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox5.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("60");}
if(jCheckBox1.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox5.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("61");}
if(jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox5.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("62");}
if(jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected()&& jCheckBox5.isSelected() && jCheckBox6.isSelected())
{jLabel1.setText("63");}
jCheckBox1.setSelected(false);
jCheckBox2.setSelected(false);
jCheckBox3.setSelected(false);
jCheckBox4.setSelected(false);
jCheckBox5.setSelected(false);
jCheckBox6.setSelected(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
  jCheckBox1.setSelected(true);      // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
jCheckBox4.setSelected(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
jCheckBox2.setSelected(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
jCheckBox3.setSelected(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
jCheckBox5.setSelected(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
jCheckBox6.setSelected(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
